### ISSUE TITLE
Warning: Capturing 'self' strongly in this block is likely to lead to a retain cycle

### ISSUE THREAD

**Issue by iMinichrispy** [Sumi-Interactive/SIAlertView#30]
I get this warning when I try to call one of my viewcontroller methods using [self alertButton1Method] from within the sialert instance button handler. This only happens when my sialert instance is declared as a global variable (which I need to dismiss the alert at a later point). Everything works fine, I've just never encountered this warning and I'm not sure what problems it can cause down the line. Is this normal behavior, or is there something am I doing wrong?

**Comment by kyoji2** [comment]
I think it should be fine. You can use weak self to avoid this warning.
__weak __typeof(&*self)weakSelf = self;

**Comment by iMinichrispy** [comment]
Thanks, that fixes it.
