### ISSUE TITLE
SIAlertView window does not resign on iOS 8

### ISSUE THREAD

**Issue by BobReid** [Sumi-Interactive/SIAlertView#84]
The window for SIAlertView is staying around swallowing touches on iOS 8.  Only reproducible on device in release mode. 

Edit: Appears to happen on 8.0.2 but not 8.0

Anyone else seeing this?

**Comment by BobReid** [comment]
Have a workaround right now by setting the user interaction to NO on the alertWindow in the teardown method. It works but its not ideal because the alertWindow stays around in windows array.

**Comment by DmitryPR** [comment]
Confirm this is present in iOS 8.1

**Comment by ka2n** [comment]
It seems this caused by https://github.com/Sumi-Interactive/SIAlertView/issues/42#issuecomment-74877272 .
